opencv/ci-gha-workflow

.github/workflows/OCV-Android-SDK.yaml, .github/workflows/OCV-PR-3.4-iOS.yaml, .github/workflows/OCV-PR-4.x-iOS.yaml, .github/workflows/OCV-PR-5.x-iOS.yaml
Part 2 of https://github.com/opencv/ci-gha-workflow/pull/10.
=> Fixed unexpected merge step in scheduled jobs

.github/workflows/OCV-Android-SDK.yaml, .github/workflows/OCV-PR-3.4-iOS.yaml, .github/workflows/OCV-PR-4.x-iOS.yaml, .github/workflows/OCV-PR-5.x-iOS.yaml
Fixed wrong condition in https://github.com/opencv/ci-gha-workflow/pull/11
=> Fixed unexpected merge step in scheduled jobs (Pt3)

.github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml, .github/workflows/OCV-Contrib-PR-3.4-U20.yaml, .github/workflows/OCV-Contrib-PR-3.4-W10.yaml, .github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-4.x-U20.yaml, .github/workflows/OCV-Contrib-PR-4.x-W10.yaml, .github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-U20.yaml, .github/workflows/OCV-Contrib-PR-5.x-W10.yaml, .github/workflows/OCV-PR-3.4-ARM64.yaml, .github/workflows/OCV-PR-3.4-U20.yaml, .github/workflows/OCV-PR-3.4-W10.yaml, .github/workflows/OCV-PR-4.x-ARM64.yaml, .github/workflows/OCV-PR-4.x-U20.yaml, .github/workflows/OCV-PR-4.x-W10.yaml, .github/workflows/OCV-PR-5.x-ARM64.yaml, .github/workflows/OCV-PR-5.x-U20.yaml, .github/workflows/OCV-PR-5.x-W10.yaml
This PR fixes https://github.com/opencv/ci-gha-workflow/issues/7 for current workflows.
=> Continue running tests even if previous unit tests failed

.github/workflows/OCV-Contrib-PR-3.4-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-3.4-macOS-x86_64.yaml, .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml, .github/workflows/OCV-PR-3.4-macOS-ARM64.yaml, .github/workflows/OCV-PR-3.4-macOS-x86_64.yaml, .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-4.x-macOS-x86_64.yaml, .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml
=> Workflows to build and test opencv & opencv_contrib on macOS x86_64 & arm64

.github/workflows/OCV-Contrib-PR-3.4-W10.yaml, .github/workflows/OCV-Contrib-PR-4.x-W10.yaml, .github/workflows/OCV-Contrib-PR-5.x-W10.yaml, .github/workflows/OCV-PR-3.4-W10.yaml, .github/workflows/OCV-PR-4.x-W10.yaml, .github/workflows/OCV-PR-5.x-W10.yaml
- [Job](https://github.com/opencv/ci-gha-workflow/runs/6781517402?check_suite_focus=true) with "updated" `download_models.py` file which updates models.
- [Job](https://github.com/opencv/ci-gha-workflow/runs/6781517255?check_suite_focus=true) with the same version of `download_models.py` file which doesn't update models.
=> Extended DNN models testing on Windows

.github/workflows/OCV-PR-3.4-macOS-ARM64.yaml, .github/workflows/OCV-PR-3.4-macOS-x86_64.yaml
Failed jobs:
- [First](https://github.com/opencv/opencv/runs/6895135345?check_suite_focus=true)
- [Second](https://github.com/opencv/opencv/runs/6895135682?check_suite_focus=true)
=> Fixed whitespaces for macOS 3.4 workflows

.github/workflows/OCV-DNN-models-update.yaml
- Workflow with updating: https://github.com/opencv/ci-gha-workflow/runs/7139255265?check_suite_focus=true#step:5:17
- Workflow without updating: https://github.com/opencv/ci-gha-workflow/runs/7139410785?check_suite_focus=true#step:5:17
=> DNN models nightly updates

.github/workflows/OCV-Contrib-PR-3.4-U14.yaml, .github/workflows/OCV-PR-3.4-U14.yaml
Depends on https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/10
=> Workflow for 3.4 branch using Ubuntu 14.04

.github/workflows/OCV-Nightly-docs-js.yaml, .github/workflows/OCV-PR-3.4-docs.yaml, .github/workflows/OCV-PR-4.x-docs.yaml, .github/workflows/OCV-PR-5.x-docs.yaml, .github/workflows/OCV-PR-docs.yaml
Depends on https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/8
=> Pipelines for docs (PR) and docs-js (nightly) builds

.github/workflows/OCV-PR-3.4-W10.yaml, .github/workflows/OCV-PR-4.x-W10.yaml, .github/workflows/OCV-PR-5.x-W10.yaml
Examples of failed pipelines:
1. https://github.com/opencv/opencv/runs/7879810965?check_suite_focus=true#step:9:24
2. https://github.com/opencv/opencv/runs/7783205591?check_suite_focus=true#step:9:24
=> Fix opencv_contrib merge issue on Windows

.github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml, .github/workflows/OCV-Contrib-PR-3.4-macOS-ARM64.yaml, .github/workflows/OCV-PR-3.4-ARM64.yaml, .github/workflows/OCV-PR-3.4-macOS-ARM64.yaml
Some of QRCode tests has been fixed in https://github.com/opencv/opencv/pull/22382
=> Remove QRCode tests from gtest_filter for 3.4 pipelines

.github/workflows/OCV-PR-3.4-docs.yaml, .github/workflows/OCV-PR-4.x-docs.yaml, .github/workflows/OCV-PR-5.x-docs.yaml
Depends on https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/11
The job with working script is [here](https://github.com/opencv/ci-gha-workflow/runs/7918571493?check_suite_focus=true#step:15:21). It was done using opencv_extra fork from https://github.com/opencv/opencv/pull/22241
=> Fix patch size checks

.github/workflows/OCV-Contrib-PR-3.4-U14.yaml, .github/workflows/OCV-Contrib-PR-3.4-U20.yaml, .github/workflows/OCV-Contrib-PR-4.x-U20.yaml, .github/workflows/OCV-Contrib-PR-5.x-U20.yaml, .github/workflows/OCV-PR-3.4-Android.yaml, .github/workflows/OCV-PR-3.4-U14.yaml, .github/workflows/OCV-PR-3.4-U20.yaml, .github/workflows/OCV-PR-4.x-Android.yaml, .github/workflows/OCV-PR-4.x-U20.yaml, .github/workflows/OCV-PR-5.x-Android.yaml, .github/workflows/OCV-PR-5.x-U20.yaml
Disabling it in case of issues on the host.
=> Temporarily disabled Linux x86_64 builds

.github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml, .github/workflows/OCV-Contrib-PR-3.4-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-3.4-macOS-x86_64.yaml, .github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml, .github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml, .github/workflows/OCV-PR-3.4-ARM64.yaml, .github/workflows/OCV-PR-3.4-iOS.yaml, .github/workflows/OCV-PR-3.4-macOS-ARM64.yaml, .github/workflows/OCV-PR-3.4-macOS-x86_64.yaml, .github/workflows/OCV-PR-4.x-ARM64.yaml, .github/workflows/OCV-PR-4.x-iOS.yaml, .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-4.x-macOS-x86_64.yaml, .github/workflows/OCV-PR-5.x-ARM64.yaml, .github/workflows/OCV-PR-5.x-iOS.yaml, .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml
Disabling it in case of issues with the network.
=> Temporarily disabled unstable builds (Linux ARM64, macOS ARM64 / x86_64)

.github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml, .github/workflows/OCV-Contrib-PR-3.4-macOS-ARM64.yaml, .github/workflows/OCV-PR-3.4-ARM64.yaml, .github/workflows/OCV-PR-3.4-macOS-ARM64.yaml
remove Objdetect_QRCode_Close.regression/0 test from gtest_filter for 3.4 pipelines
=> remove Objdetect_QRCode_Close.regression/0 test from gtest_filter for 3.4 pipelines

.github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml, .github/workflows/OCV-Contrib-PR-3.4-U14.yaml, .github/workflows/OCV-Contrib-PR-3.4-U20.yaml, .github/workflows/OCV-Contrib-PR-3.4-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-3.4-macOS-x86_64.yaml, .github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-4.x-U20.yaml, .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml, .github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-U20.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml, .github/workflows/OCV-PR-3.4-ARM64.yaml, .github/workflows/OCV-PR-3.4-U14.yaml, .github/workflows/OCV-PR-3.4-U20.yaml, .github/workflows/OCV-PR-3.4-macOS-ARM64.yaml, .github/workflows/OCV-PR-3.4-macOS-x86_64.yaml, .github/workflows/OCV-PR-4.x-ARM64.yaml, .github/workflows/OCV-PR-4.x-U20.yaml, .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-4.x-macOS-x86_64.yaml, .github/workflows/OCV-PR-5.x-ARM64.yaml, .github/workflows/OCV-PR-5.x-U20.yaml, .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml, .github/workflows/OCV-timvx-backend-tests-4.x.yml
Depends on https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/12
=> Turn on warnings check for all platforms except windows

.github/workflows/OCV-Contrib-PR-3.4-W10.yaml, .github/workflows/OCV-Contrib-PR-4.x-W10.yaml, .github/workflows/OCV-Contrib-PR-5.x-W10.yaml, .github/workflows/OCV-PR-3.4-W10.yaml, .github/workflows/OCV-PR-4.x-W10.yaml, .github/workflows/OCV-PR-5.x-W10.yaml
Script was added in https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/13
=> Script to run videoio accuracy tests without concurrency

.github/workflows/OCV-PR-3.4-docs.yaml, .github/workflows/OCV-PR-4.x-docs.yaml, .github/workflows/OCV-PR-5.x-docs.yaml
Depends on https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/14
=> Update docker image tags for docs pipelines

.github/workflows/OCV-PR-4.x-ARM64-Debug.yaml, .github/workflows/OCV-PR-5.x-ARM64-Debug.yaml
Build for ARM without NEON and other optimizations. Perf tests and extended DNN tests are disabled to save time.
=> Test PRs in debug mode to check build and generic not optimized branches

.github/workflows/OCV-PR-4.x-ARM64-Debug.yaml, .github/workflows/OCV-PR-4.x-ARM64.yaml, .github/workflows/OCV-PR-4.x-U20-Cuda.yaml, .github/workflows/OCV-PR-4.x-U20.yaml, .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-4.x-macOS-x86_64.yaml
=> fix yaml syntax

.github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml
Related:
- https://github.com/opencv/ci-gha-workflow/pull/83
- https://github.com/opencv/ci-gha-workflow/pull/84
=> Removed QR code test filters after 4.x -> 5.x merge

.github/workflows/OCV-Contrib-PR-4.x-U20.yaml, .github/workflows/OCV-Contrib-PR-5.x-U20.yaml, .github/workflows/OCV-PR-4.x-U20.yaml, .github/workflows/OCV-PR-5.x-U20.yaml
Merge with https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/16
=> Update Ubuntu 20.04 to test with libraw

.github/workflows/OCV-PR-4.x-iOS.yaml
This is probably the reason why https://github.com/opencv/opencv/issues/23610 is happening.
=> Fix wrong target branch in the iOS 4.x pipeline

.github/workflows/OCV-PR-5.x-iOS.yaml
@asmorkalov It looks like the same error is in the OpenCV 5 iOS workflow :sweat_smile:
=> Fix branch in OpenCV 5.x iOS CI

.github/workflows/OCV-PR-4.x-W10-Vulkan.yaml, .github/workflows/OCV-PR-4.x-macOS-ARM64-Vulkan.yaml
related PR: https://github.com/opencv/opencv/pull/23349
And the Vulkan patch has passed all test in my fork repo: https://github.com/zihaomu/opencv/pull/1.
NOTE: for now, we do not have very good optimization on discrete graphics GPU by Vulkan. 
The time to pass all tests on Windows 10 CI will increase by about 3 minutes. And for ARM Mac CI, the increasing time is negligible.
=> DNN: turn on Vulkan backend at Win and Mac CI

.github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-4.x-U20.yaml, .github/workflows/OCV-Contrib-PR-4.x-W10.yaml, .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml
Related changes in opencv_contrib: https://github.com/opencv/opencv_contrib/pull/3497
Related changes in main repo: https://github.com/opencv/opencv/pull/23666
=> Removed dedicated barcode module test after module integration to objdetect

.github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-U20.yaml, .github/workflows/OCV-Contrib-PR-5.x-W10.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml, .github/workflows/OCV-PR-5.x-ARM64-Debug.yaml, .github/workflows/OCV-PR-5.x-ARM64.yaml
Related PR in main repo: https://github.com/opencv/opencv/pull/23718
- Removed barcode module tests as it was migrated to objdetect
- Removed QR code test blacklist
=> Sync 4.x and 5.x after branches merge

.github/workflows/OCV-PR-4.x-U20-OpenVINO.yaml
Environment: https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/19
=> Added CI pipeline with OpenVINO.

.github/workflows/OCV-PR-4.x-U20-OpenVINO.yaml
Fixes https://github.com/opencv/opencv/issues/24336
=> Fixed concurrency group name in OpenVINO builds

.github/workflows/OCV-Contrib-PR-4.x-RISCV.yaml, .github/workflows/OCV-PR-4.x-RISCV.yaml
waiting for https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/20
=> RISC-V workflows: initial version

.github/workflows/OCV-Contrib-PR-4.x-RISCV.yaml, .github/workflows/OCV-PR-4.x-RISCV.yaml
Stored git config is not available because of HOME variable change.
=> RISC-V: fix git merge

.github/workflows/OCV-Nightly-RISCV.yaml
Compiler: T-Head GCC 1.x
Test board: LicheePi 4A
=> RISC-V: added nightly builder for RVV 0.7.1

.github/workflows/OCV-PR-4.x-Android.yaml
Requires:
- https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/26
- https://github.com/opencv/opencv/pull/24473
=> Switched to Android build tools v30 and Gradle 7.5.1.

.github/workflows/OCV-PR-5.x-Android.yaml
Needed for https://github.com/opencv/opencv/pull/24862
=> Migrate 5.x builds for Android to SDK v30

.github/workflows/OCV-PR-4.x-Android-Test.yaml
Looks like device fall a sleep time to time
=> Identify Android Phone and print CPU details before test to refresh adb session

.github/workflows/OCV-4.x-Android-SDK.yaml
Merge after https://github.com/opencv/opencv/pull/24969
=> Force Gradle to use offline mode

.github/workflows/OCV-PR-5.x-Android.yaml
Merge after https://github.com/opencv/opencv/pull/24981
=> Use Gradle offline mode in 5.x

.github/workflows/OCV-PR-5.x-ARM64-Debug.yaml, .github/workflows/OCV-PR-5.x-ARM64.yaml, .github/workflows/OCV-PR-5.x-RISCV.yaml, .github/workflows/OCV-PR-5.x-U20-Cuda.yaml, .github/workflows/OCV-PR-5.x-U20.yaml, .github/workflows/OCV-PR-5.x-U22.yaml, .github/workflows/OCV-PR-5.x-W10-Vulkan.yaml, .github/workflows/OCV-PR-5.x-W10.yaml, .github/workflows/OCV-PR-5.x-macOS-ARM64-Vulkan.yaml, .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml
Merge after https://github.com/opencv/opencv/pull/24981
=> Force OPENCV_TEST_REQUIRE_DATA in CI environments in 5.x

.github/workflows/OCV-PR-5.x-Android.yaml
Merge after:
- https://github.com/opencv/ci-gha-workflow/pull/134
- https://github.com/opencv/opencv/pull/24862
=> Build and test AAR in 5.x

.github/workflows/OCV-4.x-Android-SDK.yaml, .github/workflows/OCV-PR-5.x-Android.yaml
Requires https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/33
=> Added warning check to Android SDK build

.github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-U20.yaml, .github/workflows/OCV-Contrib-PR-5.x-U22.yaml, .github/workflows/OCV-Contrib-PR-5.x-W10.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
For https://github.com/opencv/opencv_contrib/pull/3649
=> Removed Aruco module (contrib) from CI

.github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-U20.yaml, .github/workflows/OCV-Contrib-PR-5.x-U22.yaml, .github/workflows/OCV-Contrib-PR-5.x-W10.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
Moved objdetect CascadeClassifier and HOGDescriptor to contrib xobjdetect, add accuracy and performance tests for xobjdetect.
=> Move objdetect HaarCascadeClassifier and HOGDescriptor to contrib xobjdetect

.github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
=> Fixed YAML issue in 5.x contrib OSX precommit

.github/workflows/OCV-Contrib-PR-4.x-U24.yaml, .github/workflows/OCV-PR-4.x-U24.yaml
Related docker: https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/37
=> Added default pipeline with Ubuntu 24.04.

.github/workflows/OCV-Nightly-RISCV.yaml
Missing part of #176
Upgrade main image in nightly builders too.
=> RISC-V: fix image in nightly workflow

.github/workflows/OCV-Contrib-PR-4.x-U24.yaml, .github/workflows/OCV-PR-4.x-U24.yaml
=> Downgrade saving Java test report step to gret rid of sporadic network failures

.github/workflows/OCV-PR-5.x-W10-UWP.yaml
=> build: add precommit WinRT/UWP build for 5.x branch

.github/workflows/OCV-PR-4.x-U24.yaml, .github/workflows/OCV-PR-5.x-U24.yaml
Related to https://github.com/opencv/opencv/pull/26379
=> Enable Jpeg XL by default ub Ubuntu 24.04

.github/workflows/OCV-PR-5.x-ARM64-Debug.yaml, .github/workflows/OCV-PR-5.x-ARM64.yaml, .github/workflows/OCV-PR-5.x-U20.yaml, .github/workflows/OCV-PR-5.x-U22.yaml, .github/workflows/OCV-PR-5.x-U24.yaml
Relates https://github.com/opencv/opencv/pull/26302
=> 5.x: add options to enable gpu in containers

.github/workflows/OCV-Contrib-PR-5.x-U20.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
Two pipelines had formatting issues causing "Invalid workflow file" error.
=> Fix 5.x opencv_contrib pipelines

.github/workflows/OCV-PR-4.x-W10-Vulkan.yaml, .github/workflows/OCV-PR-4.x-loongnix-loongarch64.yaml, .github/workflows/OCV-PR-4.x-macOS-ARM64-Vulkan.yaml, .github/workflows/OCV-PR-5.x-ARM64-Debug.yaml, .github/workflows/OCV-PR-5.x-U24.yaml
=> Fixed JUnit artifact names for some jobs, disabled some tests

.github/workflows/OCV-Contrib-PR-5.x-W10.yaml, .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml, .github/workflows/OCV-PR-5.x-W10-Vulkan.yaml, .github/workflows/OCV-PR-5.x-W10.yaml, .github/workflows/OCV-PR-5.x-macOS-ARM64-Vulkan.yaml, .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml, scripts/test-plan-5.x.json
Tested in https://github.com/opencv/opencv/pull/26987
=> 5.x: Update videoio test filters for Win and OSX

.github/workflows/OCV-PR-Linux.yaml, docker/ubuntu/Dockerfile-24
Should be merged with https://github.com/opencv/opencv/pull/27029
=> Updated ubuntu 24 image: added openblas

.github/workflows/OCV-PR-4.x-docs.yaml, .github/workflows/OCV-PR-5.x-docs.yaml, .github/workflows/OCV-timvx-backend-tests-4.x.yml
Related to https://github.com/actions/runner-images/issues/11101
=> Drop Ubuntu 20.04 runners as they are deprecated by Github Actions.
