opencv/ci-gha-workflow

- .github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-3.4-U20.yaml
- .github/workflows/OCV-Contrib-PR-3.4-W10.yaml
- .github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-4.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-5.x-W10.yaml
- .github/workflows/OCV-PR-3.4-ARM64.yaml
- .github/workflows/OCV-PR-3.4-U20.yaml
- .github/workflows/OCV-PR-3.4-W10.yaml
- .github/workflows/OCV-PR-4.x-ARM64.yaml
- .github/workflows/OCV-PR-4.x-U20.yaml
- .github/workflows/OCV-PR-4.x-W10.yaml
- .github/workflows/OCV-PR-5.x-ARM64.yaml
- .github/workflows/OCV-PR-5.x-U20.yaml
- .github/workflows/OCV-PR-5.x-W10.yaml
- .github/workflows/OCV-timvx-backend-tests-4.x.yml
It was fixed only for 3.4 branch in https://github.com/opencv/opencv/pull/21986 and https://github.com/opencv/opencv/pull/21998, updated for other branches also.
In addition, added `paths` to not to run workflows which weren't changed.
Fixed `if` condition to setup infra environment.
> Fixed paths on Windows builds for 4.x and 5.x branches

- .github/workflows/OCV-Android-SDK.yaml
- .github/workflows/OCV-PR-3.4-iOS.yaml
- .github/workflows/OCV-PR-4.x-iOS.yaml
- .github/workflows/OCV-PR-5.x-iOS.yaml
This is strange, but `github.event.repository.name` is unavailable when your workflow is triggered on schedule.
Failed job with a skipped setting up the environment variable: https://github.com/opencv/ci-gha-workflow/runs/6734573311?check_suite_focus=true
> Fixed environment variable for scheduled job

- .github/workflows/OCV-Contrib-PR-3.4-W10.yaml
- .github/workflows/OCV-Contrib-PR-3.4-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-3.4-W10.yaml
- .github/workflows/OCV-PR-3.4-macOS-ARM64.yaml
- .github/workflows/OCV-PR-4.x-W10.yaml
- .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-5.x-W10.yaml
- .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml
This PR:
- Turns off OpenCL for macOS ARM64 workflows
- Changes a list of filtered tests on macOS ARM64
- Adds timeouts for DNN updates on Windows
> Fix macOS ARM64 tests in case of OpenCL

- .github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-3.4-U20.yaml
- .github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-U20.yaml
- .github/workflows/OCV-PR-3.4-ARM64.yaml
- .github/workflows/OCV-PR-3.4-U20.yaml
- .github/workflows/OCV-PR-4.x-ARM64.yaml
- .github/workflows/OCV-PR-4.x-U20.yaml
- .github/workflows/OCV-PR-5.x-ARM64.yaml
- .github/workflows/OCV-PR-5.x-U20.yaml
- .github/workflows/OCV-timvx-backend-tests-4.x.yml
Faced an issue when pull strategy doesn't work if we define it inside docker globally.
- Known issue: https://github.com/actions/runner/issues/863
- Failed job: https://github.com/opencv/opencv/runs/7076063907?check_suite_focus=true#step:7:37
- Passed job: https://github.com/opencv/ci-gha-workflow/runs/7076634011?check_suite_focus=true#step:8:28
> Defined a proper HOME path as a first step for workflows in a container 

- .github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-3.4-U20.yaml
- .github/workflows/OCV-Contrib-PR-3.4-W10.yaml
- .github/workflows/OCV-Contrib-PR-3.4-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-3.4-macOS-x86_64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-4.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-5.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
- .github/workflows/OCV-PR-3.4-ARM64.yaml
- .github/workflows/OCV-PR-3.4-U20.yaml
- .github/workflows/OCV-PR-3.4-W10.yaml
- .github/workflows/OCV-PR-3.4-macOS-ARM64.yaml
- .github/workflows/OCV-PR-3.4-macOS-x86_64.yaml
- .github/workflows/OCV-PR-4.x-ARM64.yaml
- .github/workflows/OCV-PR-4.x-U20.yaml
- .github/workflows/OCV-PR-4.x-W10.yaml
- .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-4.x-macOS-x86_64.yaml
- .github/workflows/OCV-PR-5.x-ARM64.yaml
- .github/workflows/OCV-PR-5.x-U20.yaml
- .github/workflows/OCV-PR-5.x-W10.yaml
- .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml
The script to print is put under the git_cache directory on each machine. We can put it in a new location in a new environment variable (lets call it `tools` or something else) but it requires GHA registered on every machine.
OpenCV wiki page on CI configuration is also updated: https://github.com/opencv/opencv/wiki/CI-configuration.
Progress:
> Print system information in the first step for workflows with self-hosted runners

- .github/workflows/OCV-Contrib-PR-3.4-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-3.4-U20.yaml
- .github/workflows/OCV-Contrib-PR-3.4-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-3.4-macOS-x86_64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
- .github/workflows/OCV-PR-3.4-ARM64.yaml
- .github/workflows/OCV-PR-3.4-U20.yaml
- .github/workflows/OCV-PR-3.4-macOS-ARM64.yaml
- .github/workflows/OCV-PR-3.4-macOS-x86_64.yaml
- .github/workflows/OCV-PR-4.x-ARM64.yaml
- .github/workflows/OCV-PR-4.x-U20.yaml
- .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-4.x-macOS-x86_64.yaml
- .github/workflows/OCV-PR-5.x-ARM64.yaml
- .github/workflows/OCV-PR-5.x-U20.yaml
- .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml
- Linux x86_64 (5 runners): `8 threads` 
- Linux ARM64 (6 runners): `16 threads` 
- macOS x86_64 (4 runners): `3 threads` 
- macOS ARM64 (3 runners): `2 threads`
> Defined parallel threads for builds and tests on Linux and macOS

- .github/workflows/OCV-Contrib-PR-3.4-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-3.4-macOS-x86_64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
- .github/workflows/OCV-PR-3.4-macOS-ARM64.yaml
- .github/workflows/OCV-PR-3.4-macOS-x86_64.yaml
- .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-4.x-macOS-x86_64.yaml
- .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml
The previous state created a folder `$OPENCV_CI_HOME` and there was a wrong path to DNN models if it overrides with `$OPENCV_CI_HOME/new-dnn-models`.
- Workflow variable: `OPENCV_DNN_TEST_DATA_PATH=$OPENCV_CI_HOME/new-dnn-models` works properly with the full path
- Local variable: `OPENCV_DNN_TEST_DATA_PATH='$OPENCV_CI_HOME/new-dnn-models'` doesn't work properly in case of `''`
> Fix defining a path for a local variable on macOS

- .github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-4.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml
Pipelines with this test using https://github.com/opencv/opencv_contrib/pull/3335:
- [Linux ARM64](https://github.com/opencv/ci-gha-workflow/actions/runs/3159144616/jobs/5142005945)
- [Linux x86_64](https://github.com/opencv/ci-gha-workflow/actions/runs/3159144618/jobs/5142006203)
- [macOS ARM64](https://github.com/opencv/ci-gha-workflow/actions/runs/3159144615/jobs/5142005933)
- [macOS x86_64](https://github.com/opencv/ci-gha-workflow/actions/runs/3159144614/jobs/5142005947)
- [Windows10](https://github.com/opencv/ci-gha-workflow/actions/runs/3159144620/jobs/5142005934)
> Add imgaug tests for contrib workflows

- .github/workflows/OCV-PR-4.x-Android.yaml
- .github/workflows/OCV-PR-5.x-Android.yaml
This PR prevents failures in downloading gradle components (e.g. [log-1](https://github.com/opencv/opencv/actions/runs/3157746946/jobs/5143666618#step:10:2291), [log-2](https://github.com/opencv/ci-gha-workflow/actions/runs/3162491731/jobs/5149138619#step:10:2288))
Another label for a runner was created in case of parallelism issue, gradle cache cannot be used by several jobs ([log](https://github.com/opencv/ci-gha-workflow/actions/runs/3173571879/jobs/5169336043#step:10:52510)).
> Gradle cache for android workflows

- .github/workflows/OCV-PR-5.x-W10-Vulkan.yaml
- .github/workflows/OCV-PR-5.x-macOS-ARM64-Vulkan.yaml
Requires https://github.com/opencv/opencv/pull/23718
> Enable Vulkan tests for 5.x branch after 4.x->5.x merge.

- .github/workflows/OCV-PR-4.x-Android.yaml
Allows to cache files downloaded by cmake during Android builds.
> Android: use binaries cache

- .github/workflows/OCV-Contrib-PR-4.x-RISCV.yaml
- .github/workflows/OCV-PR-4.x-RISCV.yaml
Looks like it's a git quirk/bug, because it does not make any commits with `pull --no-ff --no-rebase --no-commit` but requires user name/email to be set.
> RISC-V: set git committer via environment

- .github/workflows/OCV-Contrib-PR-4.x-O22-CANN.yaml
Base image: https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/24
Added CI pipeline with openEuler22.03.SP2 and Ascend310
> Added CI pipeline with openEuler22.03.SP2 and Ascend310

- .github/workflows/OCV-PR-4.x-Android.yaml
Requires: https://github.com/opencv/opencv/pull/24752
- The new arifacts build from SDK contians Javadoc, SDK package and meta-information for publishing. 
- The old AAR package and repo contains hacked pre-fab for OpenCV linkage in C/C++ code.
> Fixed Android SDK release and added more maven artifacts.

- .github/workflows/OCV-PR-4.x-Android.yaml
Without the fix Gradle project build cases invalid URL issue.
> Revert Gradle download URL from local CI location back to official URL

- .github/workflows/OCV-PR-4.x-Android.yaml
Related patch to py script: https://github.com/opencv/opencv/pull/24849
> Drop AAR build directly from SDK as it's not needed any more

- .github/workflows/OCV-Nightly-RISCV.yaml
Should be tested after merging https://github.com/opencv/opencv/pull/24841 (merging to 5.x too?)
Skipped test set has been reduced for an experiment, further tuning might be necessary.
> RISC-V: updated weekly build for new intrinsics implementation

- .github/workflows/OCV-Contrib-PR-4.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-O22-CANN.yaml
- .github/workflows/OCV-Contrib-PR-4.x-RISCV.yaml
- .github/workflows/OCV-Contrib-PR-4.x-U20-Cuda.yaml
- .github/workflows/OCV-Contrib-PR-4.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-4.x-U22.yaml
- .github/workflows/OCV-Contrib-PR-4.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml
- .github/workflows/OCV-PR-4.x-ARM64-Debug.yaml
- .github/workflows/OCV-PR-4.x-ARM64.yaml
- .github/workflows/OCV-PR-4.x-RISCV.yaml
- .github/workflows/OCV-PR-4.x-U20-Cuda.yaml
- .github/workflows/OCV-PR-4.x-U20-OpenVINO.yaml
- .github/workflows/OCV-PR-4.x-U20.yaml
- .github/workflows/OCV-PR-4.x-U22.yaml
- .github/workflows/OCV-PR-4.x-W10-Vulkan.yaml
- .github/workflows/OCV-PR-4.x-W10.yaml
- .github/workflows/OCV-PR-4.x-macOS-ARM64-Vulkan.yaml
- .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-4.x-macOS-x86_64.yaml
Documentation: https://docs.opencv.org/4.x/d6/dea/tutorial_env_reference.html
Issue example:
```
[ RUN      ] Test_ONNX_nets.YOLONas/0, where GetParam() = OCV/CPU
[     SKIP ] OpenCV tests: Can't find data file: dnn/onnx/models/yolo_nas_s.onnx
[       OK ] Test_ONNX_nets.YOLONas/0 (0 ms)
```
CI: https://github.com/opencv/opencv/actions/runs/7395727245/job/20119459301?pr=24809
> Force OPENCV_TEST_REQUIRE_DATA in CI environments in 4.x

- .github/workflows/OCV-PR-5.x-ARM64-Debug.yaml
- .github/workflows/OCV-PR-5.x-ARM64.yaml
- .github/workflows/OCV-PR-5.x-U20.yaml
- .github/workflows/OCV-PR-5.x-U22.yaml
- .github/workflows/OCV-PR-5.x-W10.yaml
- .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml
Delete the accuracy test of ml, since it is moved to opencv_contrib from 5.0.
> Move ml to opencv_contrib

- .github/workflows/OCV-Contrib-PR-5.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-5.x-U22.yaml
- .github/workflows/OCV-Contrib-PR-5.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
Related to:
- https://github.com/opencv/opencv_contrib/pull/3636
- https://github.com/opencv/ci-gha-workflow/pull/151
> Run ML module tests in contrib after migration.

- .github/workflows/OCV-Contrib-PR-4.x-macOS-x86_64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
Build is killed by timeout sometimes.
Example: https://github.com/opencv/opencv_contrib/actions/runs/8108486330/job/22161791260?pr=3642
> Increase timeout for MacOS Intel builds in contrib

- .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml
same as https://github.com/opencv/ci-gha-workflow/pull/160
resolves https://github.com/opencv/opencv/actions/runs/8244911397/job/22563065173
required for https://github.com/opencv/opencv/pull/25197
> Increase build timeout for OCV-PR-5.x-macOS-x86_64.yaml

- .github/workflows/OCV-Nightly-RISCV.yaml
Build using clang (same as in precommit), test on CanMV-K230 board.
> RISC-V: added RVV 1.0 weekly build

- .github/workflows/OCV-Contrib-PR-4.x-RISCV.yaml
- .github/workflows/OCV-Contrib-PR-5.x-RISCV.yaml
- .github/workflows/OCV-Nightly-RISCV.yaml
- .github/workflows/OCV-PR-4.x-RISCV.yaml
- .github/workflows/OCV-PR-5.x-RISCV.yaml
Updated image: https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/38
> RISC-V: upgrade CI image to use clang 17

- .github/workflows/OCV-Nightly-RISCV.yaml
See https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/45
**Note**: also disabled two new calib tests which fail on RISC-V platforms
> RISC-V: update SC image to 2024-09

- .github/workflows/OCV-Contrib-PR-5.x-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-U20.yaml
- .github/workflows/OCV-Contrib-PR-5.x-U22.yaml
- .github/workflows/OCV-Contrib-PR-5.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-Contrib-PR-5.x-macOS-x86_64.yaml
- .github/workflows/OCV-PR-5.x-ARM64-Debug.yaml
- .github/workflows/OCV-PR-5.x-ARM64.yaml
- .github/workflows/OCV-PR-5.x-U20.yaml
- .github/workflows/OCV-PR-5.x-U22.yaml
- .github/workflows/OCV-PR-5.x-U24.yaml
- .github/workflows/OCV-PR-5.x-W10.yaml
- .github/workflows/OCV-PR-5.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-5.x-macOS-x86_64.yaml
_features2d_ is renamed to _features_.
Main PR: opencv/opencv: https://github.com/opencv/opencv/pull/26405
> Rename features2d to features

- .github/workflows/OCV-4.x-Android-SDK.yaml
Requires https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/41
Requires https://github.com/opencv/opencv/pull/26057
Related issue: https://github.com/opencv/opencv/issues/26072
> Switch to Android Build tools 34 and NDK 26d.

- .github/workflows/OCV-PR-4.x-ARM64-Debug.yaml
Fixes
```
/usr/bin/docker exec  9a73f4e46ebdf1bc51ec67674734e30ea266abfdf19d783f14ff43c9e22b9ac5 sh -c "cat /etc/*release | grep ^ID"
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
> Fixed name collision in upload artifacts

- .editorconfig
- .github/workflows/OCV-PR-Linux.yaml
- checkout-and-merge/action.yaml
- configure-and-build/action.yml
- run-tests/action.yml
- scripts/runner.py
- scripts/test-plan-4.x.json
- scripts/test-plan-5.x.json
- scripts/warnings-handling.py
**Changes:**
* create single workflow for multiple containerized Linux builds using matrix build (_branch_, _ubuntu version_)
* enable AVX2 for 24.04, enable plugins for 22.04, enable python limited API for 20.04
* simplify dnn models download (just run the script)
* extract separate actions for clone+merge, configure+build and test
* use grouping to make collapsible blocks and error/notice formatting to show failures in subtests
* combine build and build+contrib in single job
* check for warnings using new modified script
* add wrapper script for gtest runs (runner.py)
* use json test plan file for list of modules, filters and other options
* show only test failures and summary
* save test output as artifacts
* collect test status to markdown summary
* do not save java test results as …
> Add custom action and unified Linux build

- .github/workflows/OCV-Contrib-PR-4.x-W10.yaml
- .github/workflows/OCV-Contrib-PR-4.x-macOS-ARM64.yaml
- .github/workflows/OCV-PR-4.x-W10-Vulkan.yaml
- .github/workflows/OCV-PR-4.x-W10.yaml
- .github/workflows/OCV-PR-4.x-loongnix-loongarch64.yaml
- .github/workflows/OCV-PR-4.x-macOS-ARM64-Vulkan.yaml
- .github/workflows/OCV-PR-4.x-macOS-ARM64.yaml
- scripts/test-plan-4.x.json
videoio test filters should be changed due to https://github.com/opencv/opencv/pull/26948 modifying test names
> 4.x: Update videoio test filters for Win and OSX

- .github/workflows/OCV-Nightly-RISCV.yaml
- .github/workflows/OCV-PR-Linux.yaml
- run-tests/action.yml
- scripts/runner.py
- scripts/test-plan-riscv-4.x.json
- scripts/test-plan-riscv-5.x.json
Modified weekly RISC-V build.
Total time has increased from ~3 hrs to ~ 4.5 hrs because of extended test suite and difference in parallel strategy.
Minor changes has been made in common files, thus all extra "PR Linux" jobs run.
Compilation warnings detection is disabled for now - we need to fix them in the code first.
Also using updated SC image (https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/51)
> RISC-V: combine nightly builds into single job

- scripts/test-plan-5.x.json
MCC test (opencv_test_mcc) is removed for opencv 5.x as MCC and CCM are added to objdetect and photo modules respectively in opencv main repo.
> Removed MCC test for 5.x branch

- .github/workflows/OCV-PR-Linux.yaml
- docker/ubuntu/Dockerfile-20
- docker/ubuntu/Dockerfile-24
Requires https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/48
Ubuntu 22.04 is not touched to cover the case without OpenEXR.
> Docker update to cover OpenEXR branch.
